version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Africa/Kampala"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      flutter-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:15"
      timezone: "Africa/Kampala"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      android-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Africa/Kampala"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
